### ISSUE TITLE
upgrade runs.using to node16

### ISSUE THREAD

**Issue by jpalomar** [marocchino/tool-versions-action#18]
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

> Node 12 has been out of support since [April 2022](https://github.com/nodejs/Release/#end-of-life-releases), as a result we have started the deprecation process of Node 12 for GitHub Actions. We plan to migrate all actions to run on Node16 by Summer 2023. We will monitor the progress of the migration and listen to the community for how things are going before we define a final date.

**Comment by marocchino** [comment]
Closed with #19 merge
