### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by eddy147** [marocchino/tool-versions-action#44]
Can you please update to node.js 16?

This is the error we're getting.

_Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: tool-versions-action@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/._

Many thanks!

**Comment by marocchino** [comment]
https://github.com/marocchino/tool-versions-action/blob/master/action.yml#L20
Oh.. I thought I already did it.
Let's check again.
